repository:
  name: docker-backups-s3
  description: "Backup your Docker volumes to Amazon S3 on a pre-defined cron schedule."
  homepage: "https://hub.docker.com/r/aaronfagan/backups-s3"
  default_branch: master
  private: false
  has_issues: true
  has_wiki: false
  has_downloads: false
  has_projects: true
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true

labels:
  - name: bug
    color: CC0000
  - name: feature
    color: 336699
  # - name: first-timers-only
  #   oldname: Help Wanted # Include if renaming
