env:
  DOCKER_IMAGE: 'backups-s3'

name: 'Workflow'
on: push

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:

# Checkout Repo
      - name: Checkout - Repository
        uses: actions/checkout@master

# Cache
      - name: Docker - Buildx - Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

# Docker Hub Login
      - name: Docker - Hub - Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

# Buildx - Install
      - name: Docker - Buildx - Install
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest


# Docker Image - Tag, Build, & Push
      - name: Docker - Image - Push
        run: |
          docker buildx build --push \
            --cache-from type=local,src=/tmp/.buildx-cache \
            --cache-to type=local,dest=/tmp/.buildx-cache \
            --tag ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest \
            --platform linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64,linux/ppc64le,linux/s390x .

# # Docker Image - Tag, Build, & Push
#       - name: Docker - Image - Push
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           file: ./Dockerfile
#           platforms: linux/amd64,linux/arm/v7,linux/arm64
#           push: true
#           tags: ${{ secrets.DOCKER_USERNAME }}/${{ env.DOCKER_IMAGE }}:latest
#           # cache-from: type=local,src=/tmp/.buildx-cache
#           # cache-to: type=local,dest=/tmp/.buildx-cache
